UNARY("sin("    , 4, OP_SIN )
UNARY("cos("    , 4, OP_COS )
UNARY("tg("     , 3, OP_TAN )
UNARY("ln("     , 3, OP_LOG )
UNARY("sqrt("   , 5, OP_SQRT)
UNARY("sh("     , 3, OP_SH  )
UNARY("ch("     , 3, OP_CH  )
UNARY("arcsin(" , 7, OP_ASIN)
UNARY("arccos(" , 7, OP_ACOS)
UNARY("arctg("  , 6, OP_ATAN)